BlogBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: false
        userId:
            type: integer
            column: user_id
        createDate:
            type: datetime
            column: create_date
        updateDate:
            type: datetime
            column: update_date
    lifecycleCallbacks: {  }
